# Generated by Django 4.0.4 on 2022-06-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=50)),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
                ('date_col', models.BooleanField()),
                ('time_col', models.BooleanField()),
                ('username_col', models.BooleanField()),
                ('name_col', models.BooleanField()),
                ('tweet_col', models.BooleanField()),
                ('photos_col', models.BooleanField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
