# Generated by Django 4.0.4 on 2022-06-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='date_col',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='name_col',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='photos_col',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='time_col',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='tweet_col',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='username_col',
            field=models.BooleanField(null=True),
        ),
    ]
